export const ActionTypes = {
  APP_LOADED: "APP_LOADED",
  CHANGE_CURRENT_GOAL: "CHANGE_CURRENT_GOAL",
  CHANGE_CURRENT_RESULT: "CHANGE_CURRENT_RESULT",
  START_POMODORO: "START_POMODORO",
  PAUSE_POMODORO: "PAUSE_POMODORO",
  RESTART_POMODORO: "RESTART_POMODORO",
  FINISH_POMODORO: "FINISH_POMODORO",
  SAVE_FINISHED_POMODORO: "SAVE_FINISHED_POMODORO",
  LOAD_PAST_POMODOROS: "LOAD_PAST_POMODOROS",
  TICK: "TICK",
};
