export const ActionTypes = {
  CHANGE_CURRENT_GOAL: "CHANGE_CURRENT_GOAL",
  CHANGE_CURRENT_RESULT: "CHANGE_CURRENT_RESULT",
  START_POMODORO: "START_POMODORO",
  PAUSE_POMODORO: "PAUSE_POMODORO",
  RESTART_POMODORO: "RESTART_POMODORO",
  FINISH_POMODORO: "FINISH_POMODORO",
};
